QT  += core gui
QT  += serialport

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++11

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    Mavlink/Airside_Functions.cpp \
    main.cpp \
    mainwindow.cpp \
    serialclass.cpp

HEADERS += \
    Mavlink/Airside_Functions.hpp \
    Mavlink/Mavlink2_lib/ASLUAV/ASLUAV.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink_msg_asl_obctrl.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink_msg_aslctrl_data.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink_msg_aslctrl_debug.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink_msg_asluav_status.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink_msg_command_int_stamped.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink_msg_command_long_stamped.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink_msg_ekf_ext.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink_msg_fw_soaring_data.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink_msg_gsm_link_status.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink_msg_sens_atmos.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink_msg_sens_batmon.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink_msg_sens_mppt.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink_msg_sens_power.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink_msg_sens_power_board.h \
    Mavlink/Mavlink2_lib/ASLUAV/mavlink_msg_sensorpod_status.h \
    Mavlink/Mavlink2_lib/ASLUAV/testsuite.h \
    Mavlink/Mavlink2_lib/ASLUAV/version.h \
    Mavlink/Mavlink2_lib/ardupilotmega/ardupilotmega.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_adap_tuning.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_ahrs.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_ahrs2.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_ahrs3.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_airspeed_autocal.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_aoa_ssa.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_ap_adc.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_autopilot_version_request.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_battery2.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_camera_feedback.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_camera_status.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_compassmot_status.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_data16.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_data32.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_data64.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_data96.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_deepstall.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_device_op_read.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_device_op_read_reply.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_device_op_write.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_device_op_write_reply.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_digicam_configure.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_digicam_control.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_ekf_status_report.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_esc_telemetry_1_to_4.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_esc_telemetry_5_to_8.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_esc_telemetry_9_to_12.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_fence_fetch_point.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_fence_point.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_gimbal_control.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_gimbal_report.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_gimbal_torque_cmd_report.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_gopro_get_request.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_gopro_get_response.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_gopro_heartbeat.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_gopro_set_request.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_gopro_set_response.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_hwstatus.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_led_control.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_limits_status.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_mag_cal_progress.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_meminfo.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_mount_configure.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_mount_control.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_mount_status.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_osd_param_config.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_osd_param_config_reply.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_osd_param_show_config.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_osd_param_show_config_reply.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_pid_tuning.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_radio.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_rally_fetch_point.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_rally_point.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_rangefinder.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_remote_log_block_status.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_remote_log_data_block.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_rpm.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_sensor_offsets.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_set_mag_offsets.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_simstate.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_vision_position_delta.h \
    Mavlink/Mavlink2_lib/ardupilotmega/mavlink_msg_wind.h \
    Mavlink/Mavlink2_lib/ardupilotmega/testsuite.h \
    Mavlink/Mavlink2_lib/ardupilotmega/version.h \
    Mavlink/Mavlink2_lib/autoquad/autoquad.h \
    Mavlink/Mavlink2_lib/autoquad/mavlink.h \
    Mavlink/Mavlink2_lib/autoquad/mavlink_msg_aq_esc_telemetry.h \
    Mavlink/Mavlink2_lib/autoquad/mavlink_msg_aq_telemetry_f.h \
    Mavlink/Mavlink2_lib/autoquad/testsuite.h \
    Mavlink/Mavlink2_lib/autoquad/version.h \
    Mavlink/Mavlink2_lib/checksum.h \
    Mavlink/Mavlink2_lib/common/common.h \
    Mavlink/Mavlink2_lib/common/mavlink.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_actuator_control_target.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_actuator_output_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_adsb_vehicle.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_ais_vessel.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_altitude.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_att_pos_mocap.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_attitude.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_attitude_quaternion.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_attitude_quaternion_cov.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_attitude_target.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_auth_key.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_autopilot_state_for_gimbal_device.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_autopilot_version.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_battery_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_button_change.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_camera_capture_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_camera_fov_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_camera_image_captured.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_camera_information.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_camera_settings.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_camera_tracking_geo_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_camera_tracking_image_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_camera_trigger.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_cellular_config.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_cellular_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_change_operator_control.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_change_operator_control_ack.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_collision.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_command_ack.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_command_cancel.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_command_int.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_command_long.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_component_information.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_control_system_state.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_data_stream.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_data_transmission_handshake.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_debug.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_debug_float_array.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_debug_vect.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_distance_sensor.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_efi_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_encapsulated_data.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_esc_info.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_esc_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_estimator_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_extended_sys_state.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_fence_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_file_transfer_protocol.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_flight_information.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_follow_target.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_generator_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gimbal_device_attitude_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gimbal_device_information.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gimbal_device_set_attitude.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gimbal_manager_information.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gimbal_manager_set_attitude.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gimbal_manager_set_manual_control.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gimbal_manager_set_pitchyaw.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gimbal_manager_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_global_position_int.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_global_position_int_cov.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_global_vision_position_estimate.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gps2_raw.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gps2_rtk.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gps_global_origin.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gps_inject_data.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gps_input.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gps_raw_int.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gps_rtcm_data.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gps_rtk.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_gps_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_high_latency.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_high_latency2.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_highres_imu.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_hil_actuator_controls.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_hil_controls.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_hil_gps.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_hil_optical_flow.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_hil_rc_inputs_raw.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_hil_sensor.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_hil_state.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_hil_state_quaternion.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_home_position.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_isbd_link_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_landing_target.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_link_node_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_local_position_ned.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_local_position_ned_cov.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_local_position_ned_system_global_offset.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_log_data.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_log_entry.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_log_erase.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_log_request_data.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_log_request_end.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_log_request_list.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_logging_ack.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_logging_data.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_logging_data_acked.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mag_cal_report.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_manual_control.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_manual_setpoint.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_memory_vect.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_message_interval.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mission_ack.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mission_changed.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mission_clear_all.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mission_count.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mission_current.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mission_item.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mission_item_int.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mission_item_reached.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mission_request.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mission_request_int.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mission_request_list.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mission_request_partial_list.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mission_set_current.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mission_write_partial_list.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_mount_orientation.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_named_value_float.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_named_value_int.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_nav_controller_output.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_obstacle_distance.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_odometry.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_onboard_computer_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_open_drone_id_authentication.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_open_drone_id_basic_id.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_open_drone_id_location.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_open_drone_id_message_pack.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_open_drone_id_operator_id.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_open_drone_id_self_id.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_open_drone_id_system.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_optical_flow.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_optical_flow_rad.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_orbit_execution_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_param_ack_transaction.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_param_ext_ack.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_param_ext_ack_trimmed.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_param_ext_request_list.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_param_ext_request_read.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_param_ext_set.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_param_ext_set_trimmed.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_param_ext_value.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_param_ext_value_trimmed.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_param_map_rc.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_param_request_list.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_param_request_read.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_param_set.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_param_value.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_ping.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_play_tune.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_play_tune_v2.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_position_target_global_int.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_position_target_local_ned.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_power_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_radio_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_raw_imu.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_raw_pressure.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_raw_rpm.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_rc_channels.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_rc_channels_override.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_rc_channels_raw.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_rc_channels_scaled.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_request_data_stream.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_resource_request.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_safety_allowed_area.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_safety_set_allowed_area.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_scaled_imu.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_scaled_imu2.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_scaled_imu3.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_scaled_pressure.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_scaled_pressure2.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_scaled_pressure3.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_serial_control.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_servo_output_raw.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_set_actuator_control_target.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_set_attitude_target.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_set_gps_global_origin.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_set_home_position.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_set_mode.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_set_position_target_global_int.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_set_position_target_local_ned.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_setup_signing.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_sim_state.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_smart_battery_info.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_statustext.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_storage_information.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_supported_tunes.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_sys_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_system_time.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_terrain_check.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_terrain_data.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_terrain_report.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_terrain_request.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_time_estimate_to_target.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_timesync.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_trajectory_representation_bezier.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_trajectory_representation_waypoints.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_tunnel.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_uavcan_node_info.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_uavcan_node_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_utm_global_position.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_v2_extension.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_vfr_hud.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_vibration.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_vicon_position_estimate.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_video_stream_information.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_video_stream_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_vision_position_estimate.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_vision_speed_estimate.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_wheel_distance.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_wifi_config_ap.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_winch_status.h \
    Mavlink/Mavlink2_lib/common/mavlink_msg_wind_cov.h \
    Mavlink/Mavlink2_lib/common/testsuite.h \
    Mavlink/Mavlink2_lib/common/version.h \
    Mavlink/Mavlink2_lib/common/warg_custom_functions.h \
    Mavlink/Mavlink2_lib/icarous/icarous.h \
    Mavlink/Mavlink2_lib/icarous/mavlink.h \
    Mavlink/Mavlink2_lib/icarous/mavlink_msg_icarous_heartbeat.h \
    Mavlink/Mavlink2_lib/icarous/mavlink_msg_icarous_kinematic_bands.h \
    Mavlink/Mavlink2_lib/icarous/testsuite.h \
    Mavlink/Mavlink2_lib/icarous/version.h \
    Mavlink/Mavlink2_lib/matrixpilot/matrixpilot.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_airspeeds.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_altitudes.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_flexifunction_buffer_function.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_flexifunction_buffer_function_ack.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_flexifunction_command.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_flexifunction_command_ack.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_flexifunction_directory.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_flexifunction_directory_ack.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_flexifunction_read_req.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_flexifunction_set.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f13.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f14.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f15.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f16.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f17.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f18.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f19.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f20.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f21.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f22.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f2_a.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f2_b.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f4.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f5.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f6.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f7.h \
    Mavlink/Mavlink2_lib/matrixpilot/mavlink_msg_serial_udb_extra_f8.h \
    Mavlink/Mavlink2_lib/matrixpilot/testsuite.h \
    Mavlink/Mavlink2_lib/matrixpilot/version.h \
    Mavlink/Mavlink2_lib/mavlink_conversions.h \
    Mavlink/Mavlink2_lib/mavlink_get_info.h \
    Mavlink/Mavlink2_lib/mavlink_helpers.h \
    Mavlink/Mavlink2_lib/mavlink_sha256.h \
    Mavlink/Mavlink2_lib/mavlink_types.h \
    Mavlink/Mavlink2_lib/minimal/mavlink.h \
    Mavlink/Mavlink2_lib/minimal/mavlink_msg_heartbeat.h \
    Mavlink/Mavlink2_lib/minimal/mavlink_msg_protocol_version.h \
    Mavlink/Mavlink2_lib/minimal/minimal.h \
    Mavlink/Mavlink2_lib/minimal/testsuite.h \
    Mavlink/Mavlink2_lib/minimal/version.h \
    Mavlink/Mavlink2_lib/protocol.h \
    Mavlink/Mavlink2_lib/standard/mavlink.h \
    Mavlink/Mavlink2_lib/standard/standard.h \
    Mavlink/Mavlink2_lib/standard/testsuite.h \
    Mavlink/Mavlink2_lib/standard/version.h \
    Mavlink/Mavlink2_lib/test/mavlink.h \
    Mavlink/Mavlink2_lib/test/mavlink_msg_test_types.h \
    Mavlink/Mavlink2_lib/test/test.h \
    Mavlink/Mavlink2_lib/test/testsuite.h \
    Mavlink/Mavlink2_lib/test/version.h \
    Mavlink/Mavlink2_lib/uAvionix/mavlink.h \
    Mavlink/Mavlink2_lib/uAvionix/mavlink_msg_uavionix_adsb_out_cfg.h \
    Mavlink/Mavlink2_lib/uAvionix/mavlink_msg_uavionix_adsb_out_dynamic.h \
    Mavlink/Mavlink2_lib/uAvionix/mavlink_msg_uavionix_adsb_transceiver_health_report.h \
    Mavlink/Mavlink2_lib/uAvionix/testsuite.h \
    Mavlink/Mavlink2_lib/uAvionix/uAvionix.h \
    Mavlink/Mavlink2_lib/uAvionix/version.h \
    json.hpp \
    mainwindow.h \
    serialclass.h

FORMS += \
    mainwindow.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

DISTFILES += \
    Mavlink/CMakeLists.txt \
    Mavlink/Mavlink2_lib/CMakeLists.txt \
    Mavlink/Mavlink2_lib/message_definitions/ASLUAV.xml \
    Mavlink/Mavlink2_lib/message_definitions/all.xml \
    Mavlink/Mavlink2_lib/message_definitions/ardupilotmega.xml \
    Mavlink/Mavlink2_lib/message_definitions/autoquad.xml \
    Mavlink/Mavlink2_lib/message_definitions/common.xml \
    Mavlink/Mavlink2_lib/message_definitions/icarous.xml \
    Mavlink/Mavlink2_lib/message_definitions/matrixpilot.xml \
    Mavlink/Mavlink2_lib/message_definitions/minimal.xml \
    Mavlink/Mavlink2_lib/message_definitions/paparazzi.xml \
    Mavlink/Mavlink2_lib/message_definitions/python_array_test.xml \
    Mavlink/Mavlink2_lib/message_definitions/standard.xml \
    Mavlink/Mavlink2_lib/message_definitions/test.xml \
    Mavlink/Mavlink2_lib/message_definitions/uAvionix.xml \
    Mavlink/Mavlink2_lib/message_definitions/ualberta.xml \
    Mavlink/README.md
